apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastify-cpu-consumer
  namespace: fastify-test
spec:
  scaleTargetRef:
    name: fastify-cpu-consumer
  minReplicaCount: 2
  maxReplicaCount: 20
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 4
              periodSeconds: 15
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 60
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"
